// <auto-generated />
using System;
using DeliFHery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliFHery.Persistence.Migrations
{
    [DbContext(typeof(DeliFHeryDbContext))]
    [Migration("20251128221533_AddParcelPricingFields")]
    partial class AddParcelPricingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliFHery.Persistence.Entities.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("contacts", "delifhery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ed5825d-45df-4f23-9bd7-dfa48bb3cdb8"),
                            CustomerId = new Guid("5a6b9e21-7c74-4d3b-8a6a-1ef65c94af10"),
                            IsPrimary = true,
                            Type = "Email",
                            Value = "orders@orchard-market.example"
                        },
                        new
                        {
                            Id = new Guid("85fe89b7-8ac8-42ba-9013-38f5fe403fb0"),
                            CustomerId = new Guid("5a6b9e21-7c74-4d3b-8a6a-1ef65c94af10"),
                            IsPrimary = false,
                            Type = "Phone",
                            Value = "+1-800-555-1234"
                        },
                        new
                        {
                            Id = new Guid("df1a0a3c-92fd-4f0c-a341-1af7b7f33d72"),
                            CustomerId = new Guid("dbcd7f5b-7e9e-4c8f-9a2c-6f2b2e4c60f7"),
                            IsPrimary = true,
                            Type = "Phone",
                            Value = "+1-800-555-9876"
                        });
                });

            modelBuilder.Entity("DeliFHery.Persistence.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("customers", "delifhery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a6b9e21-7c74-4d3b-8a6a-1ef65c94af10"),
                            City = "Springfield",
                            Name = "Orchard Market",
                            Notes = "Prefers early deliveries",
                            PostalCode = "10001",
                            Street = "Sunrise Blvd 10"
                        },
                        new
                        {
                            Id = new Guid("dbcd7f5b-7e9e-4c8f-9a2c-6f2b2e4c60f7"),
                            City = "Springfield",
                            Name = "City Bakery",
                            Notes = "Call ahead when delayed",
                            PostalCode = "10002",
                            Street = "Downtown Ave 5"
                        });
                });

            modelBuilder.Entity("DeliFHery.Persistence.Entities.DeliveryOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationPostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("DistanceSurcharge")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("LengthCm")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OriginPostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SeasonalAdjustment")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("WidthCm")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("delivery_orders", "delifhery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95f44e9d-1c5a-4378-8f43-646f7414a87d"),
                            BasePrice = 10m,
                            CustomerId = new Guid("5a6b9e21-7c74-4d3b-8a6a-1ef65c94af10"),
                            DestinationPostalCode = "94107",
                            DistanceSurcharge = 2.5m,
                            HeightCm = 10m,
                            LengthCm = 30m,
                            OrderNumber = "ORD-1000",
                            OriginPostalCode = "94103",
                            ScheduledAt = new DateTimeOffset(new DateTime(2024, 4, 10, 7, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SeasonalAdjustment = 0m,
                            Status = "Created",
                            TotalPrice = 12.5m,
                            WeightKg = 2.5m,
                            WidthCm = 20m
                        },
                        new
                        {
                            Id = new Guid("d882e388-611d-49c2-9d2e-5a8bf9fa33e5"),
                            BasePrice = 15m,
                            CustomerId = new Guid("dbcd7f5b-7e9e-4c8f-9a2c-6f2b2e4c60f7"),
                            DestinationPostalCode = "94501",
                            DistanceSurcharge = 7.5m,
                            HeightCm = 15m,
                            LengthCm = 40m,
                            OrderNumber = "ORD-2000",
                            OriginPostalCode = "94016",
                            ScheduledAt = new DateTimeOffset(new DateTime(2024, 4, 10, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SeasonalAdjustment = 0m,
                            Status = "Created",
                            TotalPrice = 22.5m,
                            WeightKg = 6.2m,
                            WidthCm = 25m
                        });
                });

            modelBuilder.Entity("DeliFHery.Persistence.Entities.ContactEntity", b =>
                {
                    b.HasOne("DeliFHery.Persistence.Entities.CustomerEntity", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DeliFHery.Persistence.Entities.DeliveryOrderEntity", b =>
                {
                    b.HasOne("DeliFHery.Persistence.Entities.CustomerEntity", "Customer")
                        .WithMany("Deliveries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DeliFHery.Persistence.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
